version: '2'
services:
  activiti-cloud-connector-twitter:
      image: activiti-cloud-connector-twitter
      environment:
        - TWEET_PROCESS_DEF=tweet-processor:1:2ef2d39d-d13f-11e7-8988-0242ac140005
      external_links:
        - rabbitmq
      networks:
        - infrastructure

  activiti-cloud-connector-ranking:
      image: activiti-cloud-connector-ranking
      environment:
        - PRIZE_PROCESS_DEF=tweet-prize:1:2ef321be-d13f-11e7-8988-0242ac140005
      external_links:
        - rabbitmq
      networks:
        - infrastructure

  activiti-cloud-connector-3rd-party:
      image: activiti-cloud-connector-3rd-party
      external_links:
        - rabbitmq
      networks:
        - infrastructure

# we will join the infrastructure network defined by the infrastructure docker compose.
networks:
  infrastructure:
    external:
      name: docker_default