version: '2'
services:
  activiti-cloud-connector-twitter:
      image: activiti-cloud-connector-twitter
      environment:
        - ACT_RABBITMQ_HOST=rabbitmq
      external_links:
        - rabbitmq
      networks:
        - infrastructure
  activiti-cloud-connector-ranking:
      image: activiti-cloud-connector-ranking
      environment:
        - ACT_RABBITMQ_HOST=rabbitmq
      external_links:
        - rabbitmq
      networks:
        - infrastructure
  activiti-cloud-connector-3rd-party:
      image: activiti-cloud-connector-3rd-party
      environment:
        - ACT_RABBITMQ_HOST=rabbitmq
      external_links:
        - rabbitmq
      networks:
        - infrastructure

# we will join the infrastructure network defined by the infrastructure docker compose.
networks:
  infrastructure:
    external:
      name: docker_default
