# Default values for activitiinfrachart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: latest
  pullPolicy: Always
rb:
  name: rb-my-app
  port: 8081
  debug: false
  trace: false
  db:
    release: dbreleasename
infra:
  release:
    name: infrareleasename