version: '1'
services:
  activiti-cloud-audit:
    image: activiti/activiti-cloud-audit:latest
    links:
      - activiti-cloud-sso-idm:activiti-cloud-sso-idm
      - rabbitmq:rabbitmq
      - activiti-cloud-registry:activiti-cloud-registry
    environment:
      - ACT_AUDIT_PORT=8181