version: '2'
services:
  activiti-cloud-demo-ui:
    image: activiti/activiti-cloud-demo-ui:latest
    ports:
     - "3000:3000"
    external_links:
      - activiti-cloud-sso-idm
      - rb-my-app
    environment:
      - ACT_GATEWAY_URL=http://activiti-cloud-sso-idm:8080
      - ACT_IDM_URL=http://activiti-cloud-sso-idm:8180/auth/realms/springboot/protocol/openid-connect/token
      - ACT_IDM_CLIENT_ID=activiti
