version: '2'

services:

  activiti-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=activiti
      - POSTGRES_DB=activitidb
    volumes:
      - "pgdata:/var/lib/postgresql/data"  
    restart: unless-stopped

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80   
      - 443:443
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
     - "rabbitmq-data:/var/lib/rabbitmq"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: activiti/activiti-keycloak
    volumes:
      - ./activiti-realm.json:/opt/jboss/keycloak/activiti-realm.json
    restart: unless-stopped
    depends_on:
      - nginx

  example-runtime-bundle:
    container_name: example-runtime-bundle
    image: alexgri/crmruntimebundle:1.0
    volumes:
      - ./bpmn:/etc/bpmn
    # image: activiti/example-runtime-bundle:${VERSION}
    environment:
      # JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -noverify"
      SPRING_JMX_ENABLED: "false"
      ACT_KEYCLOAK_URL: "http://${DOCKER_IP}/auth"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SERVER_SERVLET_CONTEXT_PATH: /rb
      SPRING_DATASOURCE_URL: jdbc:postgresql://activiti-postgres:5432/activitidb
      SPRING_DATASOURCE_USERNAME: activiti
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ACT_RB_PROCESSES_PATH: "/etc/bpmn/processes/"
      ACT_RB_PROJECT_MANIFEST_PATH: "/etc/bpmn/default-project.json"
      # ACTIVITI_SECURITY_POLICIES_0_NAME: "HR Group restricted to SimpleProcess and ConnectorProcess"
      # ACTIVITI_SECURITY_POLICIES_0_GROUPS: "hr"
      # ACTIVITI_SECURITY_POLICIES_0_ACCESS: "WRITE"
      # ACTIVITI_SECURITY_POLICIES_0_SERVICENAME: "rb-my-app"
      # ACTIVITI_SECURITY_POLICIES_0_KEYS: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
      # ACTIVITI_SECURITY_POLICIES_1_NAME: "testgroup not restricted at all"
      # ACTIVITI_SECURITY_POLICIES_1_GROUPS: "testgroup"
      # ACTIVITI_SECURITY_POLICIES_1_ACCESS: "WRITE"
      # ACTIVITI_SECURITY_POLICIES_1_SERVICENAME: "rb-my-app"
      # ACTIVITI_SECURITY_POLICIES_1_KEYS: "*"
    restart: unless-stopped
    depends_on:
      - nginx
      - keycloak
      - rabbitmq 
      - activiti-postgres

volumes:
  rabbitmq-data:
  pgdata:

    
