apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-demo-ui
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-demo-ui
      labels:
        app: activiti-cloud-demo-ui
        serviceType: demo-ui
    spec:
      containers:
        - name: activiti-cloud-demo-ui
          image: activiti/activiti-cloud-demo-ui
          imagePullPolicy: Always
          env:
          - name: ACT_GATEWAY_URL
            value: "http://activiti-cloud-sso-idm-kub:30080"
          - name: ACT_IDM_URL
            value: "http://activiti-cloud-sso-idm-kub:30081/auth/realms/springboot/protocol/openid-connect/token"
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-cloud-demo-ui
  namespace: default
spec:
  selector:
    serviceType: demo-ui
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30082 # uncomment for minikube, comment for Kube
  type: NodePort #NodePort for minikube, LoadBalancer for Kube
---
