---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: infrastructure
        serviceType: message-broker
    spec:
      containers:
        - name: rabbitmq
          image: byteflair/rabbitmq-stomp
          ports:
          - containerPort: 5672
          - containerPort: 15672
          - containerPort: 61613
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-sso-idm-kub
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-sso-idm-kub
      labels:
        app: infrastructure
        serviceType: sso-idm
    spec:
      containers:
      - name: activiti-cloud-sso-idm-kub
        image: activiti/activiti-cloud-sso-idm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30081
        env:
#        - name: JAVA_OPTS
#          value: -Xmx256m -Xms256m
        - name: PORT_OFFSET
          value: "22001"
        - name: DB_VENDOR
          value: "H2"
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-cloud-sso-idm-kub
  namespace: default
spec:
  selector:
    serviceType: sso-idm
  ports:
    - port: 30081
      targetPort: 30081
      nodePort: 30081 # uncomment for minikube, comment for Kube
  type: NodePort #NodePort for minikube, LoadBalancer for Kube
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-gateway
  labels:
    app: infrastructure
    serviceType: gateway
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-gateway
      labels:
        app: infrastructure
        serviceType: gateway
    spec:
      containers:
        - name: activiti-cloud-gateway
          image: activiti/activiti-cloud-gateway:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: ACT_KEYCLOAK_URL
            value: "http://activiti-cloud-sso-idm-kub:30081/auth"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-registry
  labels:
    app: infrastructure
    serviceType: registry
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-registry
      labels:
        app: infrastructure
        serviceType: registry
    spec:
      containers:
        - name: activiti-cloud-registry
          image: activiti/activiti-cloud-registry:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8761
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: ACT_CLOUD_CONFIG_SERVER_ENABLED
            value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    serviceType: message-broker
  ports:
    - port: 5672
      name: broker
      targetPort: 5672
    - port: 15672
      name: admin
      targetPort: 15672
    - port: 61613
      name: stomp
      targetPort: 61613
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-cloud-registry
  namespace: default
spec:
  selector:
    serviceType: registry
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
  namespace: default
spec:
  selector:
    serviceType: gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # uncomment for minikube, comment for Kube
  type: NodePort #NodePort for minikube, LoadBalancer for Kube
