---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-activiti-cloud-query
  labels:
    app: infrastructure
    serviceType: query
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-query
      labels:
        app: infrastructure
        serviceType: query
    spec:
      containers:
        - name: activiti-cloud-query
          image: "activiti/activiti-cloud-query:{{ .Values.image.tag  }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8182
          env:
          - name: ACT_QUERY_PORT
            value: "8182"
          - name: ACT_QUERY_HOST
            value: "{{ .Release.Name }}-activiti-cloud-query"
          - name: ACT_KEYCLOAK_URL
            value: "http://{{ .Values.infra.release.name }}-activiti-cloud-sso-idm-kub:30081/auth"
          - name: ACT_EUREKA_URL
            value: "http://{{ .Values.infra.release.name }}-activiti-cloud-registry:8761/eureka/"
          - name: ACT_RABBITMQ_HOST
            value: "{{ .Values.infra.release.name }}-rabbitmq"
          - name: ACT_QUERY_DB_USER
            value: postgres
          - name: ACT_QUERY_DB_PASS
            value: password
          - name: ACT_QUERY_DB_PLATFORM
            value: "org.hibernate.dialect.PostgreSQLDialect"
          - name: ACT_CLOUD_CONFIG_SERVER_ENABLED
            value: "false"
          - name: SPRING_HATEOAS_USEHALASDEFAULTJSONMEDIATYPE
            value: "false"
          - name: ACT_QUERY_DB_URI
            value: jdbc:postgresql://{{ .Values.rb.db.release.name}}-{{ .Values.rb.name }}-db:5432/activitidb
          - name: JAVA_OPTS
            value: -Xmx128m -Xms128m
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-activiti-cloud-query
  namespace: default
spec:
  selector:
    serviceType: query
  ports:
    - port: 8182
      targetPort: 8182
  type: ClusterIP
