apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5000
        codec => "json_lines"
      }
    }

    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        codec => json
        user => elastic
        password => changeme
      }
    }



