apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: kibana
  name: kibana
spec:
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
    nodePort: 30339
  selector:
    name: kibana
  type: NodePort
#  type: LoadBalancer